baseURL = "https://jabezzy2000.github.io/jabezzy.github.io/"
languageCode = "en-us"
title = "My Technical Blog"
theme = "ananke"

[params]
  subtitle = "A minimalistic blog for my technical writings"
  profilePicture = "/assets/images/profile_photo.jpeg"
